excluded:
    - Pods
    - WeatherForecastTests
    - WeatherForecastUITests
    - WeatherForecast/App/AppDelegate.swift
    - WeatherForecast/App/SceneDelegate.swift
disabled_rules:
    - trailing_whitespace
    - identifier_name
line_length:
 ignores_comments: true

