# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherForecast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint', '~> 0.43.1'

  # Pods for WeatherForecast

  target 'WeatherForecastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherForecastUITests' do
    # Pods for testing
  end

end
